using System.Globalization;
using System.Text;
using SmartCertificateSystem.Models;

namespace SmartCertificateSystem.Services;

public class TranscriptPdfService
{
    private const double Left = 72;
    private const double Top = 742;
    private const double LineHeight = 18;

    public byte[] GenerateTranscriptPdf(Transcript transcript)
    {
        var studentName = transcript.Student?.FullName ?? $"Student #{transcript.StudentId}";
        var studentId = transcript.Student?.StudentId.ToString(CultureInfo.InvariantCulture) ?? transcript.StudentId.ToString(CultureInfo.InvariantCulture);
        var dateOfBirth = transcript.Student?.DateOfBirth.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture) ?? "N/A";

        var lines = new List<string>
        {
            Text(Left, Top, "F2", 20, "Academic Transcript"),
            Text(Left, Top - 30, "F1", 10, "Generated by Smart Certificate Verification & Student Records Management System"),
            Rule(Left, Top - 44, 468),
            Text(Left, Top - 76, "F2", 12, "Student Details"),
            Text(Left, Top - 98, "F1", 11, $"Name: {studentName}"),
            Text(Left, Top - 116, "F1", 11, $"Student ID: {studentId}"),
            Text(Left, Top - 134, "F1", 11, $"Date of Birth: {dateOfBirth}"),
            Text(Left, Top - 152, "F1", 11, $"Transcript Generated: {transcript.GeneratedDate:yyyy-MM-dd}"),
            Text(Left, Top - 170, "F1", 11, $"GPA: {transcript.GPA:0.00}"),
            Text(Left, Top - 206, "F2", 12, "Grades"),
            Text(Left, Top - 228, "F2", 10, "Module"),
            Text(Left + 285, Top - 228, "F2", 10, "Score"),
            Text(Left + 355, Top - 228, "F2", 10, "Grade"),
            Text(Left + 425, Top - 228, "F2", 10, "Credits"),
            Rule(Left, Top - 236, 468)
        };

        var y = Top - 258;
        foreach (var grade in transcript.Grades.OrderBy(g => g.ModuleName))
        {
            lines.Add(Text(Left, y, "F1", 10, TrimToFit(grade.ModuleName, 42)));
            lines.Add(Text(Left + 285, y, "F1", 10, grade.Score.ToString("0", CultureInfo.InvariantCulture)));
            lines.Add(Text(Left + 355, y, "F1", 10, grade.LetterGrade));
            lines.Add(Text(Left + 425, y, "F1", 10, grade.CreditValue.ToString(CultureInfo.InvariantCulture)));
            y -= LineHeight;
        }

        if (transcript.Grades.Count == 0)
        {
            lines.Add(Text(Left, y, "F1", 10, "No grades recorded."));
            y -= LineHeight;
        }

        lines.Add(Rule(Left, y - 8, 468));
        lines.Add(Text(Left, y - 32, "F1", 9, $"Generated on {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC"));

        return BuildPdf(string.Join('\n', lines));
    }

    public string BuildTranscriptFileName(Transcript transcript)
    {
        var studentName = transcript.Student?.FullName ?? $"student-{transcript.StudentId}";
        var safeName = new string(studentName
            .ToLowerInvariant()
            .Select(c => char.IsLetterOrDigit(c) ? c : '_')
            .ToArray())
            .Trim('_');

        if (string.IsNullOrWhiteSpace(safeName))
        {
            safeName = "student";
        }

        return $"{safeName}_transcript_{transcript.TranscriptId}.pdf";
    }

    private static byte[] BuildPdf(string content)
    {
        var contentLength = Encoding.ASCII.GetByteCount(content);
        var objects = new[]
        {
            "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
            "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
            "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>\nendobj\n",
            "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
            "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj\n",
            $"6 0 obj\n<< /Length {contentLength} >>\nstream\n{content}\nendstream\nendobj\n"
        };

        var document = new StringBuilder("%PDF-1.4\n");
        var offsets = new List<int> { 0 };

        foreach (var pdfObject in objects)
        {
            offsets.Add(Encoding.ASCII.GetByteCount(document.ToString()));
            document.Append(pdfObject);
        }

        var xrefStart = Encoding.ASCII.GetByteCount(document.ToString());
        document.Append("xref\n0 7\n");
        document.Append("0000000000 65535 f \n");
        foreach (var offset in offsets.Skip(1))
        {
            document.Append(offset.ToString("D10", CultureInfo.InvariantCulture)).Append(" 00000 n \n");
        }

        document.Append("trailer\n<< /Size 7 /Root 1 0 R >>\n");
        document.Append("startxref\n");
        document.Append(xrefStart.ToString(CultureInfo.InvariantCulture)).Append('\n');
        document.Append("%%EOF\n");

        return Encoding.ASCII.GetBytes(document.ToString());
    }

    private static string Text(double x, double y, string font, int size, string text) =>
        $"BT /{font} {size} Tf 1 0 0 1 {Format(x)} {Format(y)} Tm ({Escape(text)}) Tj ET";

    private static string Rule(double x, double y, double width) =>
        $"q 0.5 w {Format(x)} {Format(y)} m {Format(x + width)} {Format(y)} l S Q";

    private static string Escape(string value)
    {
        var cleaned = new StringBuilder(value.Length);
        foreach (var c in value)
        {
            cleaned.Append(c switch
            {
                '(' => "\\(",
                ')' => "\\)",
                '\\' => "\\\\",
                >= ' ' and <= '~' => c,
                _ => '?'
            });
        }

        return cleaned.ToString();
    }

    private static string TrimToFit(string value, int maxLength) =>
        value.Length <= maxLength ? value : $"{value[..Math.Max(0, maxLength - 3)]}...";

    private static string Format(double value) => value.ToString("0.##", CultureInfo.InvariantCulture);
}
